version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z kafka 9092"]
      interval: 10s
      timeout: 5s
      retries: 10

  postgres:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  resume_service:
    build:
      context: ./resume_service
    ports:
      - "8001:8001"
    depends_on:
      kafka:
        condition: service_healthy
    restart: always

  jd_service:
    build:
      context: ./jd_service
    ports:
      - "8002:8002"
    depends_on:
      kafka:
        condition: service_healthy
    restart: always

  match_service:
    build:
      context: ./match_service
    depends_on:
      kafka:
        condition: service_healthy
    restart: always
